#! /usr/bin/python3
import sys
import os
import subprocess
import psutil
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--remote', action='store_true', default=False)
opt = parser.parse_args()

if opt.remote:

    queue = 'sharedq'
    cmd = ['/etc/guacamole/sinfo', '-p', queue, '-N', '-o', '%n', '--noheader']
    p = subprocess.run(cmd, stdout=subprocess.PIPE)
    s = p.stdout.decode()
    nodes = s.split('\n')
    nodes = [n for n in nodes if len(n)>0]
    print('Nodes in the VNC queue:', nodes)

    procs = []
    for host in nodes:
        cmd = ['ssh',
               '-F', '/etc/guacamole/tomcat/ssh_config',
               '-i', '/etc/guacamole/tomcat/id_createvnc_computenode',
               'create-vnc@'+host,
               '/etc/guacamole/list-vnc-all']
        print(' '.join(cmd))
        p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True)
        procs.append((host, p))
    rtn = 0
    for host,p in procs:
        s,e = p.communicate()
        lines = s.split('\n')
        for x in lines + e.split('\n'):
            if len(x):
                print('#', host, x)
        lines = [line for line in lines if line.startswith(':')]
        for line in lines:
            print(host, line)
        if p.returncode != 0:
            rtn = p.returncode
    sys.exit(rtn)

for proc in psutil.process_iter():
    cmd = proc.cmdline()
    if len(cmd) == 0:
        continue
    #print(cmd)
    #print(proc.cmdline())
    #['/usr/bin/Xvnc', ':1', '-auth', '/home/akogios/.Xauthority', '-desktop', 'cn001:1 (akogios)', '-fp', '/usr/share/fonts/X11//misc,/usr/share/fonts/X11//Type1', '-geometry', '1024x768', '-pn', '-rfbauth', '/home/akogios/.vnc/passwd', '-rfbport', '5901', '-rfbwait', '30000']

    if cmd[0] != '/usr/bin/Xvnc':
        continue

    port = cmd[1]
    if not port.startswith(':'):
        continue

    user = proc.username()

    print('%s %s' % (port, user))
    
    # guac = False
    # for word in cmd:
    #     #print('Cmdline: ', word)
    #     if word.endswith('passwd-guac'):
    #         #print('PASSWD-GUAC!')
    #         guac = True
    # print('%s %s' % (words[0], 'T' if guac else 'F'))
