#! /usr/bin/python3
import sys
import os
import subprocess
import psutil
import argparse

def remote():
    base = '/etc/guacamole'
    queue = 'sharedq'
    cmd = [os.path.join(base, 'sinfo'), '-p', queue, '-N', '-o', '%n', '--noheader']
    p = subprocess.run(cmd, stdout=subprocess.PIPE)
    s = p.stdout.decode()
    nodes = s.split('\n')
    nodes = [n for n in nodes if len(n)>0]
    print('Nodes in the VNC queue:', nodes)

    procs = []
    for host in nodes:
        cmd = ['ssh',
               '-F', os.path.join(base, 'tomcat/ssh_config'),
               '-i', os.path.join(base, 'tomcat/id_createvnc_computenode'),
               'create-vnc@'+host,
               os.path.join(base, 'list-vnc-all')]
        print(' '.join(cmd))
        p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True)
        procs.append((host, p))
    rtn = 0
    for host,p in procs:
        s,e = p.communicate()
        lines = s.split('\n')
        for x in lines + e.split('\n'):
            if len(x):
                print('#', host, x)
        lines = [line for line in lines if line.startswith(':')]
        for line in lines:
            print(host, line)
        if p.returncode != 0:
            rtn = p.returncode
    return rtn

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--remote', action='store_true', default=False)
    opt = parser.parse_args()

    if opt.remote:
        return remote()

    for proc in psutil.process_iter():
        cmd = proc.cmdline()
        if len(cmd) == 0:
            continue
        # Search for VNC sessions whose command-lines look like this:
        #['/usr/bin/Xvnc', ':1', '-auth', '/home/akogios/.Xauthority', '-desktop', 'cn001:1 (akogios)', '-fp', '/usr/share/fonts/X11//misc,/usr/share/fonts/X11//Type1', '-geometry', '1024x768', '-pn', '-rfbauth', '/home/akogios/.vnc/passwd', '-rfbport', '5901', '-rfbwait', '30000']

        if cmd[0] != '/usr/bin/Xvnc':
            continue

        port = cmd[1]
        if not port.startswith(':'):
            continue

        # Search for "-rfbauth <password-file>"
        passwd_fn = None
        for a1,a2 in zip(cmd, cmd[1:]):
            if a1 == '-rfbauth':
                passwd_fn = a2
                break

        user = proc.username()
        print('%s %s %s' % (port, user, passwd_fn))

    return 0

if __name__ == '__main__':
    sys.exit(main())
