#! /bin/bash

echo "list-vnc-for $@"
echo "running as: $(whoami)"

user=$1
shift
if [ "$1x" == "--remotex" ]; then
    /etc/guacamole/list-vnc --remote $user
else
    sudo --set-home --user=$user /etc/guacamole/list-vnc
    # "$@"
fi
