#! /usr/bin/python3
import sys
import os
import subprocess
import time

# first chdir to my home dir
homedir = os.path.expanduser('~')
os.chdir(homedir)

vncdir = os.path.expanduser('~/.vnc/')
if not os.path.exists(vncdir):
    try:
        os.makedirs(vncdir)
    except:
        pass
passwdfn = os.path.expanduser('~/.vnc/passwd-guac')
passwd = 'GUAC'
passwd = passwd.encode()
cmd = ['/usr/bin/tigervncpasswd', '-f', '>', passwdfn]
print('Running: ', ' '.join(cmd))
p = subprocess.run(cmd, input=passwd, shell=True,
                   stdout=subprocess.PIPE, stderr=subprocess.PIPE)
#print('Return code from tigervncpasswd:', p.returncode, 'stdout', p.stdout, 'stderr', p.stderr)
cmd = ['/usr/bin/tigervncserver', '-passwd', passwdfn]
# '-verbose', '-noreset',
print('Running: ', ' '.join(cmd))
p = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
#print('Result of tigervncserver:', p.returncode)
print(p.stdout.decode())

print()
print()
print()
print("A window should now pop up saying that you have been Disconnected.")
print()
print("Please use the 'Home' button, AND THEN RELOAD THE PAGE, to see your new Remote Desktop.")
print()
print()
time.sleep(3)


