#! /bin/bash

echo Starting VNC for: $@
echo I am $(whoami)
#echo SSH original command: $SSH_ORIGINAL_COMMAND

user=$1

sudo --set-home --non-interactive --user=$user /etc/guacamole/start-vnc

echo
echo
echo
echo "A window should now pop up saying that you have been Disconnected."
echo
echo "Please use the 'Home' button to begin using your new Remote Desktop."
echo
echo
sleep 3
echo
